### ISSUE TITLE
Can't create FC host, vdisk limitation?, Documentation. 

### ISSUE THREAD

**Issue by olemyk** [ansible-collections/ibm.spectrum_virtualize#1]
##### SUMMARY

Dokumentation is missing. and cant create FC/SCSI hosts.

##### ISSUE TYPE
- Bug Report
 have found most of the details by looking into the python code and examples there.
I'm guessing that the documentation will be updated soon?

1.  When creating hosts, the remove/absent is working but not create a host for me. `getting error: CMMVC5867E The action failed because the worldwide port name is already assigned or is not valid.`
 However when I'm using the same **fcwwpn** when creating it manually that works fine.
Have tried different wwpn.   ISCSI is working.
 if i create the host manually and run playbook it will run the play without errors.
 `fatal: [localhost]: FAILED! => {"changed": false, "msg": {"code": 500, "data": {"fcwwpn": "10000000C9609C78", "iogrp": "0:1:2:3", "name": "db2hotel2", "protocol": "scsi"}, "err": ["HTTPError %s", "HTTP Error 500: Internal Server Error"], "out": "\"Command error occurred; error code 1: CMMVC5867E The action failed because the worldwide port name is already assigned or is not valid. \"", "url": "https://10.10.10.56:7443/rest/mkhost"}}`
 

2. And The example in the python script is with protocol: `"FC"` this should be ´SCSI´

3. For Creating volumes: 
 I don't see any values for creating other volumes then thick. Is this  Virtualize RestApi limit?

Info:  I have tested this on a SVC cluster with code 8.3.0.1 (soon upgrading to 8.3.1) and use the example in Python module. 

##### ANSIBLE VERSION

```
ansible 2.9.4
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

---
- name: Using the IBM Spectrum Virtualize collection to create an FC host
  hosts: localhost
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  tasks:
    - name: Define a new FC host
      ibm_svc_host:
        clustername: 10.10.10.56
        domain:
        username: xxx
        password: xx
        log_path: //Users/olemyk/IdeaProjects/ansible-sandbox/logs/playbook.debug
        name: db2hotel2
        state: present
        fcwwpn: 10000000C9609C78
        iogrp: 0:1:2:3
        protocol: scsi   #wrong in detail
        type: generic
```

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": {"code": 500, "data": {"fcwwpn": "10000000C9609C78", "iogrp": "0:1:2:3", "name": "db2hotel2", "protocol": "scsi"}, "err": ["HTTPError %s", "HTTP Error 500: Internal Server Error"], "out": "\"Command error occurred; error code 1: CMMVC5867E The action failed because the worldwide port name is already assigned or is not valid. \"", "url": "https://10.10.10.56:7443/rest/mkhost"}}
```
