### ISSUE TITLE
Support authentication through token

### ISSUE THREAD

**Issue by freedge** [ansible-collections/ibm.spectrum_virtualize#12]
##### SUMMARY
The idea would be to be able to specify a token (such as the one returned as X-Auth-Token after a POST to /auth) instead of username/password. This would prevent extra calls to the auth API, it would also make sure we are not uselessly creating sessions on the SVC side.

In addition, it would be much awesome if we could retrieve this token through the SSH cli. The idea would be to use the cli for the sole purpose of getting a token, that can be reuse after for Ansible playbooks. For security reasons, we usually favor authentication through SSH key exchange, so it would be a nice improvement here as well.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
the login mechanism

##### ADDITIONAL INFORMATION

```yaml
   serial:1
   - tasks:
      ibm_svc_host:
        clustername: '{{ svc_ip }}'
        token: "{{ lookup('env','IBMSVC_TOKEN') }}"
```
