### ISSUE TITLE
Getting fatal error when creating host.

### ISSUE THREAD

**Issue by autocoder10** [ansible-collections/ibm.spectrum_virtualize#31]
##### SUMMARY
When running a create host playbook using ibm_svc_host py module, got a fatal error and showing as Failed but creating the host entry.

**Error:**
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Module failed. Error [argument of type 'NoneType' is not iterable]."}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ibm_svc_host

##### ANSIBLE VERSION

```paste below
ansible 2.9.17
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- name: Using the IBM Spectrum Virtualize collection
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost

  vars:
    clustername: testcluster
    username: ansibletest
    password: passw0rd

  tasks:
    - name: Create host entry
      ibm_svc_host:
        clustername: "{{clustername}}"
        domain:
        username: "{{ username }}"
        password: "{{ password }}"
        log_path: /tmp/svcplaybook.debug
        validate_certs: false
        name: test1
        state: present
        fcwwpn: 11223344556633AA:11223344556633BB
        iogrp: 0
        protocol: scsi
        type: generic
```

##### ACTUAL RESULTS

```paste below
2021-03-08T14:35:39.209  INFO 140378744436544 ibm_svc_host.py:apply():372 CHANGED: host does not exist, but requested state is 'present'
2021-03-08T14:35:39.209  INFO 140378744436544 ibm_svc_host.py:host_create():272 creating host 'test1'
2021-03-08T14:35:39.209  INFO 140378744436544 ibm_svc_host.py:host_create():290 creating host command '11223344556633AA:11223344556633BB' opts 'generic'
```
