### ISSUE TITLE
can not restore flashcopy snapshot - ibm.spectrum_virtualize.ibm_svc_manage_flashcopy

### ISSUE THREAD

**Issue by scheurer13** [ansible-collections/ibm.spectrum_virtualize#69]
##### SUMMARY
I'm trying to create a Flashcopy mapping using the ibm.spectrum_virtualize.ibm_svc_manage_flashcopy module.
Goal is to clone the existing snapshot to the original. So target already exists.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

**Module** 

```
ibm.spectrum_virtualize.ibm_svc_manage_flashcopy module
```

**Task**

```
- name: restore_snap_hana | Create FlashCopy mapping for snapshot SVC1
  ibm.spectrum_virtualize.ibm_svc_manage_flashcopy:
    clustername: "asvc0001"
    username: "{{ svc_username }}"
    password: "{{ svc_password }}"
    log_path: /tmp/playbook.debug
    state: present
    name: "restore-{{ item }}"
    copytype: clone
    source: "{{ item }}_snap"
    target: "{{ item }}"
    mdiskgrp: P01_flash_fl921
    consistgrp: "{{ SID }}_restore"
    copyrate: 50
    force: yes
  loop: "{{ SVC1.stdout_lines }}"
```

 "msg": "target [sps9105_TESTdata_vol1] already exists."

##### ANSIBLE VERSION

```
ansible [core 2.11.8]
  config file = /etc/ansible/ansible_es/ansible.cfg
  configured module search path = ['/home/schetr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  ansible collection location = /etc/ansible/ansible_es
  executable location = /usr/bin/ansible
  python version = 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  jinja version = 2.11.2
  libyaml = False
```

##### COLLECTION VERSION

```
Collection              Version
----------------------- -------
ibm.spectrum_virtualize 1.9.0
```

##### OS / ENVIRONMENT
```
Distributor ID: openSUSE
Description:    openSUSE Leap 15.4
Release:        15.4
```

##### STEPS TO REPRODUCE

```
- name: restore_snap_hana | Create FlashCopy mapping for snapshot SVC1
  ibm.spectrum_virtualize.ibm_svc_manage_flashcopy:
    clustername: "asvc0001"
    username: "{{ svc_username }}"
    password: "{{ svc_password }}"
    log_path: /tmp/playbook.debug
    state: present
    name: "restore-{{ item }}"
    copytype: clone
    source: "{{ item }}_snap"
    target: "{{ item }}"
    mdiskgrp: P01_flash_fl921
    consistgrp: "{{ SID }}_restore"
    copyrate: 50
    force: yes
  loop: "{{ SVC1.stdout_lines }}"
```

##### EXPECTED RESULTS
Mapping should be created.

Working SVCTASK

```
svctask mkfcmap -name restore-{{ item }} -autodelete -cleanrate 50 -consistgrp {{ item }}_restore -copyrate 50 -source {{ item }}_snap -target {{ item }}
```

##### ACTUAL RESULTS

```
ok: [sps91051] => (item=sps9105_TESTdata_vol1) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "clustername": "asvc0001",
            "consistgrp": "TEST_restore",
            "copyrate": "50",
            "copytype": "clone",
            "domain": null,
            "force": true,
            "grainsize": null,
            "log_path": "/tmp/playbook.debug",
            "mdiskgrp": "P01_flash_fl921",
            "name": "restore-sps9105_TESTdata_vol1",
            "noconsistgrp": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "source": "sps9105_TESTdata_vol1_snap",
            "state": "present",
            "target": "sps9105_TESTdata_vol1",
            "token": null,
            "username": "fcm",
            "validate_certs": false
        }
    },
    "item": "sps9105_TESTdata_vol1",
    "msg": "target [sps9105_TESTdata_vol1] already exists."
}
```
