### ISSUE TITLE
I want to start a  backup fcgroup (incremental copy) and it do nothing

### ISSUE THREAD

**Issue by NicolaeCh** [ansible-collections/ibm.spectrum_virtualize#76]
##### SUMMARY

I want to start a  backup fcgroup (incremental copy) and it do nothing

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ibm.spectrum_virtualize.ibm_svc_start_stop_flashcopy
##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    ibm.spectrum_virtualize.ibm_svc_start_stop_flashcopy:
      clustername: "{{item.0}}"
      username: "{{usuario}}"
      password: "{{pass}}"
      name: "{{item.1}}"
      isgroup: true
```

##### EXPECTED RESULTS

CG must be started

##### ACTUAL RESULTS

"msg": "FlashCopy Consistency Group [CLON] is in [idle_or_copied] state.",
  "changed": false,
  "invocation": {
    "module_args": {
      "clustername": "10.66.22.98",
      "username": "ansible",
      "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "name": "CLON",
      "isgroup": true,
      "state": "started",
      "validate_certs": false,
      "domain": null,
      "log_path": null,
      "token": null,
      "force": null

```paste below

```
