### ISSUE TITLE
ibm_svc_mdisk can't configure distributed array

### ISSUE THREAD

**Issue by kunamashina** [ansible-collections/ibm.spectrum_virtualize#81]
##### SUMMARY

I tried to configure IBM FlashSystem 5000 series with ibm_svc_mdisk but failed because the storage unit only supports distributed raid arrays, standard raid is not configurable at all.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ibm_svc_mdisk
##### ANSIBLE VERSION

```paste below
ansible [core 2.14.1]
python version = 3.10.8
jinja version = 3.1.2
```

##### COLLECTION VERSION

```paste below
ibm.spectrum_virtualize 1.10.0
```

##### CONFIGURATION

```paste below
[defaults]
inventory = inventory
```

##### OS / ENVIRONMENT

IBM Flashsystem 5000 version 8.4.0.8 (build 152.24.2207280736000)

##### STEPS TO REPRODUCE

Run a task with ibm_svc_mdisk module to configure a raid level on a disk array for IBM FlashSystem 5000

```yaml
- name: Create disk array and set raid level
      ibm_svc_mdisk:
          clustername: "{{ clustername }}"
          token: "{{ result.token }}"
          log_path: "{{ logpath }}"
          name: "{{ array_name }}"
          state: present
          level: raid5
          drive: 0:1:2:3:4
          encrypt: false
          mdiskgrp: "{{ pool_name }}"
```

##### EXPECTED RESULTS

I expected the array to be configured with raid5 but the flashsystem 5000 doesn't support non distributed raid level. There's no way to address distributed raid 5 in the module

##### ACTUAL RESULTS

The playbook runs until this point, then it fails because the module doesn't support non-distributed RAID arrays

```paste below
fatal: [192.168.1.160]: FAILED! => {"changed": false, "msg": {"code": 500, "data": {"drive": "0:1:2:3:4", "encrypt": "no", "level": "raid6", "name": "Array0"}, "err": ["HTTPError %s", "HTTP Error 500: "], "out": "\"Command error occurred; error code: 1, error text: CMMVC9642E The command failed because non-distributed RAID arrays are not supported for this IO group. \"", "url": "https://192.168.1.160:7443/rest/mkarray/Pool0"}}
```
![non-distributed_raid](https://user-images.githubusercontent.com/23556119/207932070-c92f130d-0a18-44e6-80fe-86ed1f4fe4d3.png)
