### ISSUE TITLE
Support additional volume group and snapshot features (info, rename, assign)

### ISSUE THREAD

**Issue by lszomor** [ansible-collections/ibm.spectrum_virtualize#92]
##### SUMMARY
Hi
Would it be possible to add additional features regarding volume groups and snapshots? I'd like to have support for the following features:
* Gathering volume group and snapshot information. 
* Volume group rename capability
* An override flag to manage a mirrored volume

We are introducing FlashSystem arrays into our environment. We will depend on these features in our daily operations.
I've implemented all the features for our internal use. Please find the links for them in the additional information section.

Thank you!
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

* ibm_svc_info   
* ibm_svc_manage_volumegroup 
* ibm_svc_manage_volume

###### Gathering volume group and snapshot information
Commit: https://github.com/lszomor/ibm.spectrum_virtualize/commit/acd2584eb7d45250777e7321c986e1cdbc04b3b0

```yaml
- name: Get volume group and snapshot info
  ibm.spectrum_virtualize.ibm_svc_info:
    clustername: "{{clustername}}"
    domain: "{{domain}}"
    username: "{{username}}"
    password: "{{password}}"
    log_path: /tmp/ansible.log
    gather_subset: 
      - snapshot
      - volumegroup
```      

###### Volume group rename capability
Commit: https://github.com/lszomor/ibm.spectrum_virtualize/commit/109058bfd31371473f2065645c5df286960948bc

```yaml
- name: Rename an existing volume group
  ibm.spectrum_virtualize.ibm_svc_manage_volumegroup:
    clustername: "{{ clustername }}"
    domain: "{{ domain }}"
    username: "{{ username }}"
    password: "{{ password }}"
    log_path: /tmp/playbook.debug
    old_name: vg0
    name: new_vg0_name
    state: present
```
    
###### An override flag to manage a mirrored volume
Commit: https://github.com/lszomor/ibm.spectrum_virtualize/commit/9afe007d9483ed346e65b71af81f1d3b429a897a

```yaml
- name: Assign a Mirrored volume to a Volume Group
  ibm.spectrum_virtualize.ibm_svc_manage_volume:
    clustername: "{{ clustername }}"
    domain: "{{ domain }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name: "volume_name"
    volumegroup: "test_volumegroup"
    force: true
    state: "present"
```
